export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED'
export const AUTHENTICATION_RESPONSE = 'AUTHENTICATION_RESPONSE'

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED'
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE'